name: browser_routes
description: General Purpose In-Browser Routing. Null safe.
version: 1.0.0

environment:
  sdk: '>=2.12.0-13.0.dev <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  test_api: ^0.2.19-nullsafety.6
